### PR TITLE
Update example-article.json

### PR DESCRIPTION
**Pull request by Roshack**
Update example-article.json to include a spec for the API request for an author profile.

### CODE REVIEW

**Comment by KarimBaaba** [comment]
Was about to ask the same question on the forums, thanks for bringing this up.

Shouldn't the resource be `http://service/author/userid` as stated in [project.org](https://github.com/abramhindle/CMPUT404-project-socialdistribution/blob/master/project.org)?

We also have a similar response with a few more attributes.
- email
- first_name
- last_name
- github_username
- image

Of course, all of these are optional but the point here is to have a useful page to show when viewing a foreign profile.

Thanks!

**Comment by Roshack** [comment]
Yeah you're definitely right about the URI, I messed that one up. Yeah all
those fields probably could/should go into the return JSON.

**Comment by KarimBaaba** [comment]
Another two attributes that should probably be included..
````
"friends": [],
"followers": []
```
Since they're public information anyways.

**Comment by derekdowling** [comment]
Yeah, providing a list of at least friends would make this a lot simpler.

**Comment by KarimBaaba** [comment]
@abramhindle any feedback on this? Potentially a big portion of integration.

**Comment by abramhindle** [comment]
You don't necessarily know who's following you. The other profile attributes seem alright.

**Comment by abramhindle** [comment]
Merged in another pull request.

**Pull request closed without merging**
