### PR TITLE
Standardization Of Implementation Spec

### PR DESCRIPTION
**Pull request by derekdowling**
For next year's group, this standardizes the spec making it a lot more consistent and sane to implement. Encourages reusability of logic for posts/comments, as well as adhering to JSON and JS standards. Also fixes whitespacing in this document. Further additions:

* Confirm all "id" references as UUIDs
* JSON camelCasing of object keys
* Changes "content-type" to "contentType" for easier parsing in languages
* Comments have a "contentType" so that they can be better formatted
* Removes text/html as a possible "contentType" to prevent XSS
* changes "pubDate" to "published"and the formatting is confirmed as a ISO 8601 DateTime
* spec for HATEOS "github" url in author objects
* format spacing to consistent 4 spaces

### CODE REVIEW

**Comment by derekdowling** [comment]
This needs to be rebased into one commit before being merged.

**Comment by abramhindle** [comment]
Unix timestamps do not include timezone. I was also trying to stay as close as possible to RSS.

JSON indentation is also inconsistent on "getpost". Avoiding tabs means the files look the same all the time.

So if you fix the indentation and drop the timezoneless utime I think we're almost good to go.

**Comment by derekdowling** [comment]
@abramhindle I've flattened this down and taken into account both your feedback and that from today's lecture.

**Comment by abramhindle** [comment]
I have merged this pull request into branch 2016 for next year. Thanks for your clarifications.

https://github.com/abramhindle/CMPUT404-project-socialdistribution/commit/de2b497de3220a2aa13d3c6e94d2321ef61ea5c2

**Comment by derekdowling** [comment]
Perfect, glad to help.

**Pull request closed without merging**
